### ISSUE TITLE
Comunica engine doesnt resolve promise

### ISSUE THREAD

**Issue by AronBuzogany** [SolidLabResearch/generic-data-viewer#20]
Using test query with id ```123``` in the [config file](https://github.com/SolidLabResearch/generic-data-viewer/blob/main/src/config.json), currently on branch [login-authentication](https://github.com/SolidLabResearch/generic-data-viewer/tree/login-authentication) we can reconstruct the following example cases. 

- Case 1
  - Execute query.
  - Results are shown, works as expected.
- Case 2
  - Log in.
  - Execute query.
  - No results are shown, the source doesn't allow authenticated fetch
- Case 3 
  - Log in.
  - Logout.
  - Execute query.
  - Results are shown, works as expected
- Case 4
  - Log in. 
  - Execute query.
  - No results are shown, the source doesn't allow authenticated fetch
  - Log out.
  - Execute query.
  - No response after engine.query(...), the promise doesn't resolve nor reject, infinite loop? 

The promise seems never to resolve or reject. I have found this by placing console.logs() after both cases, neither of them actually happened. 

I have also tested these cases on [Comunica jQuery widget](https://query.linkeddatafragments.org/). Although we cannot be sure, they seem to result in similar results.

**Comment by pheyvaer** [comment]
Can you test this with data sources that are actual Solid pods?

**Comment by AronBuzogany** [comment]
Haven't done this with Solid pods, but I created a custom fetch function that simply throws an error:

```js
function myFetch(arg){
  throw new Error("fail")
}
```
When using this fetch as the fetch function of ```myEngine.query``` the same issue occurs. So when using Solid pods if the fetch function throws an error or the Comunica engine throws an error on the fetch the issue above will occur.

**Comment by pheyvaer** [comment]
But why would the fetch fail in the first place?

**Comment by AronBuzogany** [comment]
I haven't yet found a failing example with a Solid pod though and when looking into if pods can disallow authenticated fetch (failing example of this issue, the authenticated fetch fails) I do not find anything on this.

**Comment by pheyvaer** [comment]
A pod will only say if you have access (200) or not (401 or 403), but the fetch itself should not a throw an error because of that.

**Comment by AronBuzogany** [comment]
In that case I don't think this issue applies to Solid pods.

**Comment by pheyvaer** [comment]
Did you already report this in the Comunica repo?

**Comment by AronBuzogany** [comment]
> Did you already report this in the Comunica repo?

I have placed an issue in their repo:

- https://github.com/comunica/comunica/issues/1236
