### ISSUE TITLE
Results from previous query are shown when clicking on another querry before the initial query is finished executing

### ISSUE THREAD

**Issue by AronBuzogany** [SolidLabResearch/generic-data-viewer#4]
As the query results are pipelined into the results table in a asynchronous way it is possible to have 2 queries run asynchronously which would result in both results getting shown in the table as such:

![image](https://github.com/SolidLabResearch/generic-data-viewer/assets/108480125/6d64e25e-420b-4998-bff2-af78fdbe25b7)

Ideally we would want the initial query to stop executing.

**Comment by pheyvaer** [comment]
Don't you mean "asynchronous" instead of "synchronous", because if it's "synchronous" I would expect not issues actually?

**Comment by AronBuzogany** [comment]
This has been solved in PR #14
