### ISSUE TITLE
Make screencast

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/generic-data-viewer#43]
Once everything is done, we also need a screencast showing how the app works.

**Comment by AronBuzogany** [comment]
[Screencast from 31-07-23 10:25:54.webm](https://github.com/SolidLabResearch/generic-data-viewer/assets/108480125/c8658551-28a2-4b85-9654-75eb38a2cef7)

Is this what you had in mind? Or should there be a video showing configuration etc. as well? Any other feedback?

**Comment by pheyvaer** [comment]
You don't need to add the configuration, but it does need have audio with an explanation of what is happening. At the beginning there should also be an intro with what the app is and what it's goal is.

**Comment by pheyvaer** [comment]
How can you make a demo if I didn't say that everything was done? This is what the issue says:

> Once everything is done

**Comment by pheyvaer** [comment]
@AronBuzogany Now that all important issues are done, can you create the screencast? Uploading to WeTransfer is ok, but I will afterwards upload it to the IDLab cloud.

**Comment by AronBuzogany** [comment]
> @AronBuzogany Now that all important issues are done, can you create the screencast? Uploading to WeTransfer is ok, but I will afterwards upload it to the IDLab cloud.

I am on it!

**Comment by AronBuzogany** [comment]
[This link](https://we.tl/t-2fxcJ6ZCOR) contains the current screencast

**Comment by pheyvaer** [comment]
Looks great! This is the public link on our cloud https://cloud.ilabt.imec.be/index.php/s/AJomCGpLjYbxmCX

Can you add the link to the README via a PR? Thanks.

**Comment by AronBuzogany** [comment]
I have made an issue #67  and a PR #68  for it.

**Comment by pheyvaer** [comment]
This could have just been this issue, but ok.
