### ISSUE TITLE
Add Web app logo href to configuration file 

### ISSUE THREAD

**Issue by AronBuzogany** [SolidLabResearch/generic-data-viewer#44]

**Comment by AronBuzogany** [comment]
@pheyvaer is this something we need or is this kind of configuration unnecessary?

**Comment by pheyvaer** [comment]
Isn't the logo already part of the config file via `logoLocation`?

**Comment by AronBuzogany** [comment]
> Isn't the logo already part of the config file via `logoLocation`?

The logo is, I meant the href for the logo, to for example redirect to the company website

**Comment by pheyvaer** [comment]
Yeah that would be nice to add, but low priority for now.
