### ISSUE TITLE
Refresh button text outside box

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/generic-data-viewer#50]
When viewing the app on a smaller screen the refresh buttons looks like this

<img width="137" alt="image" src="https://github.com/SolidLabResearch/generic-data-viewer/assets/9413528/479f30e8-877d-46dc-95f5-faea9a022486">

The HTML body has a width of 1440 and height of 762 on that specific screen.

**Comment by pheyvaer** [comment]
I might not had taken the latest styling of the app. I used a private window though. When checking it with the `resizable-columns` branch I get the following:

<img width="846" alt="image" src="https://github.com/SolidLabResearch/generic-data-viewer/assets/9413528/d41e6aa8-0b1b-4309-abdc-8ee12a1b70b5">

**Comment by pheyvaer** [comment]
The button is ok, but now the logo has no padding at the top and bottom (anymore).

**Comment by AronBuzogany** [comment]
> The button is ok, but now the logo has no padding at the top and bottom (anymore).

Is this still the case on main?
