### ISSUE TITLE
Errors when importing "@solid/community-server"

### ISSUE THREAD

**Issue by AronBuzogany** [SolidLabResearch/generic-data-viewer#51]
When I try to import "@solid/community-server" I get the a lot of errors: 

![image](https://github.com/SolidLabResearch/generic-data-viewer/assets/108480125/e17fd320-2dc6-4d99-83bc-1b8b277cecd3)

**Comment by pheyvaer** [comment]
Did you already create an issue at the Community Solid Server repo?

**Comment by pheyvaer** [comment]
Not relevant anymore.
