### ISSUE TITLE
Add Solid login

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/generic-data-viewer#9]

**Comment by AronBuzogany** [comment]
This issue is currently resolved, aside of issue #20 and documentation

**Comment by pheyvaer** [comment]
In what branch/commit is this resolved?

**Comment by AronBuzogany** [comment]
Currently in the [login-authentication branch](https://github.com/SolidLabResearch/generic-data-viewer/tree/login-authentication)

**Comment by AronBuzogany** [comment]
Solved and merged with #23
